name: Deploy static content to Pages

on:
  # Runs on pushes to the default branch
  push:
    branches: ['main']
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Use a version that matches your project
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build # This command creates the 'dist' folder
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # This path MUST match your build output folder
          # It's 'dist' for Vite, or 'build' for Create React App
          path: ./build

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
